DerekHill/edfu

- apps/erya/src/app/search/search.component.html
- apps/erya/src/assets/stylesheets/_main.scss
https://trello.com/c/XOtVxHoo/43-move-search-field-into-header-on-inner-pages
https://trello.com/c/4BnHQGD4/44-really-sorry-to-do-this-but-i-think-the-search-box-is-better-when-it-stays-in-the-same-place-near-the-top-rather-than-moving-to
> Move search bar into header

- apps/erya/src/app/search/search.component.html
- apps/erya/src/assets/stylesheets/_main.scss
Seems better to separate navbar and search by color
> Use another colour for subheader

- apps/erya/src/app/login/login.component.html
- apps/erya/src/styles.scss
https://trello.com/c/NGEbxAJX/46-fix-mobile-login-scrolling
> Fix login scrolling and change body background

- apps/erya/src/app/navbar/navbar.component.ts
- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/search.module.ts
- apps/erya/src/app/search/sense/sense.component.html
- apps/erya/src/app/search/sign/sign.component.html
- apps/erya/src/app/search/sign/sign.component.spec.ts
- apps/erya/src/app/search/sign/sign.component.ts
- apps/erya/src/assets/stylesheets/_main.scss
https://trello.com/c/9Ol3fWKw/48-youtube-vimeo-video-format-and-review-position-style-play-again-button
> Vimeo and Youtube videos layout

- apps/erya/src/app/contribute/contribute.component.html
- apps/erya/src/app/contribute/contribute.component.ts
- apps/erya/src/app/contribute/contribute.module.ts
- apps/erya/src/assets/stylesheets/_main.scss
- apps/erya/src/styles.scss
https://trello.com/c/TSUMKOxK/50-design-styling-of-form-to-add-sign
> Styles: Design and styling of form to add sign

- apps/erya/src/app/contribute/contribute.component.html
- apps/erya/src/app/navbar/navbar.component.html
- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/senses/senses.component.html
- apps/erya/src/assets/stylesheets/_main.scss
- apps/erya/src/styles.scss
https://trello.com/c/XWdDVtLR/60-file-validation-messages-senses-required-indicator
Added accepted file types
https://github.com/DerekHill/edfu/blob/7ec5dd93dca88d758485bf0d0acb12a9cd8fead8/apps/erya/src/app/contribute/contribute.component.html#L50
> Update: File validation messages and senses required indicator styles

- apps/erya/src/app/contribute/contribute.component.html
- apps/erya/src/app/navbar/navbar.component.html
- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/sense-selection/sense-selection.component.html
- apps/erya/src/app/shared/pipes/highlight-entry.pipe.spec.ts
- apps/erya/src/app/shared/pipes/highlight-entry.pipe.ts
- apps/erya/src/app/shared/shared.module.ts
- apps/erya/src/assets/stylesheets/_main.scss
- apps/erya/src/styles.scss
https://trello.com/c/A5VQ3xtt/36-more-clear-sense-view-orientation-using-colours-etc
> Update: Highlight entry word in example and update colours theme closer to Oxford  

- package-lock.json
- package.json
> Revert "Bump @tensorflow/tfjs from 1.7.0 to 1.7.1"

- apps/erya/src/app/contribute/contribute.component.ts
- apps/erya/src/app/graphql.module.ts
- apps/erya/src/app/search/search.component.ts
https://www.apollographql.com/docs/react/api/apollo-client/#ObservableQuery.refetch
> Use refetch instead of setVariables

- apps/erya-e2e/src/integration/app.spec.ts
- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/search.component.ts
- apps/erya/src/assets/stylesheets/_main.scss
- apps/erya/src/styles.scss
https://trello.com/c/rMcPKJnv/69-review-x-and-search-icons-in-search-box
> Update: Search field design

- apps/erya/src/app/login/login.component.html
- apps/erya/src/app/login/signup.component.html
- apps/erya/src/app/login/signup.component.ts
- apps/erya/src/app/navbar/navbar.component.html
- apps/erya/src/app/navbar/navbar.component.ts
- apps/erya/src/assets/stylesheets/_main.scss
https://trello.com/c/0tOIkxwd/86-style-signup
https://trello.com/c/hWKLgGbA/83-style-dont-have-an-account-sign-up
https://trello.com/c/K2b0nKdD/82-show-username-or-avatar-on-navbar-when-logged-in
> Update: Add styles to signup, update login and add username to navbar

- apps/erya/src/app/contribute/contribute.component.html
- apps/erya/src/app/contribute/contribute.component.ts
- apps/erya/src/assets/stylesheets/_preloader.scss
- apps/erya/src/styles.scss
https://trello.com/c/AAya9Ciw/73-on-contribute-form-deal-with-scenario-when-change-mind-about-word
Network speed: Slow 3G
> Update: Better UX on contribute

- apps/erya/src/app/contribute/contribute.component.html
- apps/erya/src/app/contribute/contribute.component.ts
- apps/erya/src/app/search/search.component.ts
- apps/erya/src/app/search/sign/sign.component.html
- apps/erya/src/app/search/sign/sign.component.spec.ts
- apps/erya/src/app/shared/components/player.component.html
- apps/erya/src/app/shared/components/player.component.ts
- apps/erya/src/app/shared/shared.module.ts
- apps/erya/src/assets/stylesheets/_main.scss
- apps/erya/src/assets/stylesheets/_preloader.scss
https://trello.com/c/DR4Qaoz1/70-what-happens-after-successful-submit-of-contribute-form
> Update: Sign upload behaviour

- apps/erya/src/app/search/sign/sign.component.ts
Cleaned sign component. Related to  https://github.com/DerekHill/edfu/pull/251
> Cleanup: Remove player logic from sign component

- apps/erya/src/app/search/sign/like/like.component.html
- apps/erya/src/app/search/sign/sign.component.html
- apps/erya/src/assets/stylesheets/_main.scss
https://trello.com/b/Hx0fM97j/edfu
> Update: Style Like as a button

- apps/api/src/app/auth/auth.controller.ts
- apps/api/src/app/auth/auth.service.ts
- apps/erya/src/app/alerts/alert-channel.service.ts
- apps/erya/src/app/alerts/alert/alert.component.scss
- apps/erya/src/app/alerts/alert/alert.component.ts
- apps/erya/src/app/alerts/alerts.module.ts
- apps/erya/src/app/alerts/alerts.typings.ts
- apps/erya/src/app/app.component.html
- apps/erya/src/app/app.component.spec.ts
- apps/erya/src/app/app.module.ts
- apps/erya/src/app/auth/auth.service.ts
- apps/erya/src/app/login/login.component.html
- apps/erya/src/app/login/login.component.ts
- apps/erya/src/app/login/signup.component.html
- apps/erya/src/app/login/signup.component.ts
- apps/erya/src/app/search/sign/like/like.component.html
- apps/erya/src/app/search/sign/like/like.component.ts
- apps/erya/src/app/shared/components/modal/modal.component.ts
- apps/erya/src/app/utils/string.utils.ts
- libs/api-interfaces/src/lib/enums.ts
- package-lock.json
- package.json
https://trello.com/c/JMUulefz/84-better-experience-if-user-enters-wrong-credentials-on-login
> Update: Alerts 

- apps/erya/src/app/alerts/alert/alert.component.scss
- apps/erya/src/app/contribute/contribute.module.ts
- apps/erya/src/app/contribute/likes-counter/likes-counter.component.html
- apps/erya/src/app/contribute/likes-counter/likes-counter.component.ts
- apps/erya/src/app/contribute/manage.component.html
- apps/erya/src/app/contribute/manage.component.ts
- apps/erya/src/app/navbar/navbar.component.html
- apps/erya/src/assets/stylesheets/_main.scss
https://trello.com/c/HRyMQPs4/97-style-manage-component
> Update: Style manage component

- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/search.component.ts
https://trello.com/c/sOpYlrKv/41-signs-see-more-variants
> Update: Display only one sign and load more buy click

- apps/erya/src/app/search/sign/sign.component.html
https://trello.com/c/cc2zttzK/72-display-optional-mnemonic-below-sign
> Update: Add mnemonic to sign

- apps/erya/src/app/search/search.component.html
- apps/erya/src/app/search/sign/sign.component.html
- apps/erya/src/app/search/sign/sign.component.spec.ts
- apps/erya/src/app/search/sign/sign.component.ts
- apps/erya/src/index.html
https://trello.com/c/vwQFRe3U/71-seo-per-sign-page
> Update: Seo per sign page

- apps/erya/src/app/navbar/navbar.component.ts
This is additional to https://github.com/DerekHill/edfu/pull/307/commits/7f7ee6c97862553f4e29180c9191e30b3ca2f669
When user login from the sign page, it will be redirected back to sign on successful login
> Update: Add redirect from navbar
